# Generated by Django 5.0.6 on 2024-06-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=250)),
            ],
        ),
    ]
