# Generated by Django 5.0.6 on 2024-06-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endapi', '0002_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='email',
            field=models.EmailField(default='admin@gmail.com', max_length=250),
        ),
        migrations.AlterField(
            model_name='admins',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$h44S0vVd7CCuz10Dpxbdom$gxbvdGxEVL66qWhtDT7NqAWJIxQqnpnzy2+h5wLV0OY=', max_length=250),
        ),
    ]
