# Generated by Django 5.0.6 on 2024-06-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endapi', '0004_alter_admins_email_alter_admins_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('message_status', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('log_type', models.CharField(max_length=50)),
            ],
        ),
    ]
