# Generated by Django 5.0.6 on 2024-06-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endapi', '0005_logentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('message_status', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('log_group', models.CharField(max_length=250)),
                ('log_id', models.CharField(max_length=50)),
            ],
        ),
    ]
