# Generated by Django 5.0.6 on 2024-06-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endapi', '0006_loggen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
        migrations.DeleteModel(
            name='LogGen',
        ),
    ]
